# Generated by Django 5.2.1 on 2025-07-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routes_data', models.JSONField()),
                ('best_distance', models.FloatField()),
                ('num_ants', models.IntegerField()),
                ('iterations', models.IntegerField()),
                ('evaporation_rate', models.FloatField()),
                ('alpha', models.FloatField()),
                ('beta', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
