# Generated by Django 5.2.1 on 2025-06-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitud_destino',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='latitud_partida',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='longitud_destino',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20),
        ),
    ]
