# Generated by Django 5.2.1 on 2025-06-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_latitud_destino_order_latitud_partida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='longitud_partida',
            field=models.CharField(default='', max_length=15),
        ),
    ]
