# Generated by Django 5.2.1 on 2025-06-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_longitud_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20),
        ),
    ]
